services:

  ### Backend ###
  usuarios_api:
    build: ./controller/usuarios
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      DB_SSL: ${DB_SSL}